# This is a basic workflow to help you get started with Actions

name: getting started 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
              echo 1. what is in this directory?
              ls -a
              echo
              echo 2. java is installed?
              java --version 
              echo 
              echo 3. is git installed?
              git --version
              echo 4. what build tools are installed?
              mvn --version
              gradle --version
              ant --version
              echo
              echo 5. where is android sdk root?
              echo $ANDROiD_SDK_ROOT
              echo 
              echo 6. what is the workspace location
              echo $RUNNER_WORKSPACE
              echo 
              echo 7. who is running script?
              whoami
              echo 8. what environment avilable?
              env
          
